### ISSUE TITLE
Draggable vertically and horizontally

### ISSUE THREAD

**Issue by frederic-mamath** [kutlugsahin/react-smooth-dnd#8] opened 2018-05-02 13:14 UTC
Hello Kutlugsahin,

I have been using your library for simple case and it's really great !

Now i have a list of items horizontally but going to a new line when there's too many element.
 
<img width="326" alt="capture d ecran 2018-05-02 a 15 09 38" src="https://user-images.githubusercontent.com/5349561/39524953-f23c144c-4e1a-11e8-997a-684dc23451d9.png">

The problem i'm meeting is that when i'm dragging items horizontally in the second row, it's taking the first row in reference and it doesn't take the good index nor position...

**Is it a bug or am I not using the library correctly ? Or is it not implemented ?**

**Comment by kutlugsahin** [comment] 2018-05-02 16:34
hi @FredericKtan ,
Unfortunately there is no support for wrapped elements by design. Elements should be placed either vertical or horizontally to make it work. So I am closing this issue

**Closed as completed by kutlugsahin** 2018-05-02 16:34 UTC
