### ISSUE TITLE
Children is object, expected array

### ISSUE THREAD

**Issue by BennievanderWel** [kutlugsahin/react-smooth-dnd#6] opened 2018-04-12 10:00 UTC
Hi,

When I have:

    class MyCmp extends React.Component {
      render() {
        return (
          <div>
            <Container onDrop={() => console.log(1)}>
              {this.state.items.map(item => {
                return (
                  <Draggable key={item.id}>
                    {item.content}
                  </Draggable>
                );
              })}
            </Container>
          </div>
        )
      }
    }
I get the error:

<code>Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `t`, expected an array.</code>

Do you have any suggestions?

Also, the console.log() in the onDrop prop is not triggered. What am I doing wrong?

**Comment by kutlugsahin** [comment] 2018-04-12 11:49
@BennievanderWel 
Hi, I could not reproduce your issue with exact same code you sent and with assuming the items array. I got console.log triggered. Is your issue persists ?
ps: Don't mind the warning it will be fixed.

**Comment by kutlugsahin** [comment] 2018-04-12 21:39
Warnings fixed in 0.3.4. I am closing the issue.

**Closed as completed by kutlugsahin** 2018-04-12 21:39 UTC
Labels: bug
