### ISSUE TITLE
Disable item "shuffling" when dragging

### ISSUE THREAD

**Issue by gargrave** [kutlugsahin/react-smooth-dnd#16] opened 2018-05-30 19:38 UTC
Hey there,

Great library! Really enjoying using it.

One thing I am wondering: is it possible to remove the "shuffling" effect when dragging an item around in the list? In other words, when I drag Item A between Items B and C, I don't want Item B to move up to allocate space for Item A. I would rather it just stay put so I can simply show a highlighted line without actually affecting the placement of the list elements.

I know I can set `animationDuration` to null to remove the _animations_, but I would like to just have them not move at all when I'm dragging.

Is this currently possible, or is it something you are willing to consider adding as an extra prop? I could potentially put together a PR to enable this if it's something you would entertain.

Thanks again!
Gabe

**Comment by kutlugsahin** [comment] 2018-05-31 08:14
Hi @gargrave ,
I am glad that you enjoy using it :) 
To answer your question, no there is no possible way to disable shuffling and by design I am not willing to add such feature. The purpose of this library to provide a natural and physical drag and drop and shuffling experience like you are moving an element for real otherwise there are some libraries that already provides the feature you are requesting :) So I am closing this issue.
Cheers !

**Closed as completed by kutlugsahin** 2018-05-31 08:14 UTC
